
name: Validate migrations
on:
  workflow_call:
    secrets:
      github-token:
        required: true
    inputs:
      github-actor:
        description: Repository id for the container
        type: string
        required: true
      image_publication_repository:
        description: Repository id for the container
        type: string
        required: true
      migrations_directory:
        description: Directory where SQL files are located
        type: string
        required: true
      migration_timestamp_version:
        description: Indicate if the migration version is usign the timestamp format
        type: boolean
        default: false
      image_publication_registry:
        description: Registry to publish the container
        type: string
        default: ghcr.io/domix
      pg_container_image:
        description: Postgres container image to be used to test the db migrations
        type: string
        default: postgres
      pg_container_tag:
        description: Postgres container tag to be used to test the db migrations
        type: string
        default: 10.17
      flyway_container_image:
        description: Flyway container image to be used to run the db migrations
        type: string
        default: flyway/flyway
      flyway_container_tag:
        description: Flyway container tag to be used to run the db migrations
        type: string
        default: 8.5.13
      pg_user:
        description: The Postgres user
        type: string
        default: postgres
      pg_password:
        description: The Postgres user password
        type: string
        default: secret
      pg_database:
        description: The Postgres database name
        type: string
        default: postgres

jobs:
  build-container:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: ${{ inputs.pg_container_image }}:${{ inputs.pg_container_tag }}
        env:
          POSTGRES_USER: ${{ inputs.pg_user }}
          POSTGRES_PASSWORD: ${{ inputs.pg_password }}
          POSTGRES_DB: ${{ inputs.pg_database }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.image_publication_registry }}
          username: ${{ inputs.github-actor }}
          password: ${{ secrets.github-token }}

      - name: Download the scripts
        run: |
          curl -o $PWD/validate_migration_version.sh https://raw.githubusercontent.com/domix/db-migrations-utils/main/validate_migration_version.sh
          curl -o $PWD/migration_util.rb https://raw.githubusercontent.com/domix/db-migrations-utils/main/migration_util.rb

      - name: Give script permissions
        run: chmod +x $PWD/validate_migration_version.sh
      
      - name: Validate migration files
        run: ./validate_migration_version.sh -d ${{ inputs.migrations_directory }} -t ${{ inputs.migration_timestamp_version }}
